# Generated by Django 3.0.3 on 2020-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('incident_description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('incident_location', models.CharField(max_length=1000)),
                ('initial_severity', models.CharField(max_length=1000)),
                ('suspected_cause', models.CharField(max_length=1000)),
                ('immediate_actions_taken', models.CharField(max_length=1000)),
                ('sub_incident_types', models.CharField(max_length=1000)),
                ('reported_by', models.CharField(max_length=1000)),
            ],
        ),
    ]
